import hashlib,json,pathlib,re,subprocess,xml.etree.ElementTree as ET
ROOT=pathlib.Path('/Users/jimmy/Documents/aiao/rxdb'); B=ROOT/'requirements/reviews/evidence/2026-10-05/parallel/frameworks'; V=B.parent/'validation'
scope=json.loads((B/'scope.json').read_text()); reads=json.loads((B/'file-inspection.json').read_text()); head=subprocess.check_output(['git','rev-parse','HEAD'],cwd=ROOT,text=True).strip()
original={}
for o in scope:
 text=(ROOT/o['plan']).read_text(); rows=[]
 for l in text.splitlines():
  if re.match(r'^\| C\d+\s*\|',l):
   p=[x.strip() for x in l.split('|')[1:-1]];rows.append({'C':p[0],'title':p[1],'action':p[2],'originalScenario':p[3]})
 original[o['object']]=rows
coverage=json.loads((B/'validation-observations.json').read_text())['results']; coverage={x['project']:x for x in coverage}
packed=json.loads((V/'packed-consumer-entry-check.json').read_text()); packs={x['project']:x for x in packed['packages']}
validation={t:json.loads((V/f'all-object-{t}-status.json').read_text()) for t in ['strict-lint','typecheck']}
log=(V/'framework-editor-coverage.txt').read_text().splitlines(); sections={}
for i,l in enumerate(log):
 m=re.search(r'> nx run ([\w-]+):test',l)
 if m:
  end=next((j for j in range(i+1,len(log)) if re.search(r'> nx run [\w-]+:',log[j])),len(log)); part=log[i:end]
  summary=[(i+j+1,t.strip()) for j,t in enumerate(part) if re.search(r'Test Files|\bTests\s+',t)]
  cases=[(i+j+1,t.strip()) for j,t in enumerate(part) if '.spec.' in t and ('✓' in t or '❯' in t)]
  sections[m[1]]={'range':[i+1,end],'summary':summary,'files':cases,'failures':[(i+j+1,t.strip()) for j,t in enumerate(part) if t.strip().startswith('FAIL ')]}

def A(path,start,end=None,role='read-implementation'):
 return {'path':path,'absolutePath':str(ROOT/path),'start':start,'end':end or start,'role':role}
def case(c,anchors,tests,proved,gaps):
 return {'C':c,'status':'partial','verdict':'局部通过，原 C 尚未完整核销' if proved else '未验证，保持 partial','anchors':anchors,'testAnchors':tests,'established':proved,'gaps':gaps}

matrix={}
for o in scope:
 n=o['object']; fw=n.rsplit('-',1)[-1]; cases=[]
 if n.startswith('rxdb-plugin-search-'):
  file='inject-search.ts' if fw=='angular' else 'use-search.ts'; path=f'packages/{n}/src/{file}'; test=f'packages/{n}/src/__tests__/'+('inject-search.spec.ts' if fw=='angular' else 'use-search.spec.ts')
  bounds={'angular':(85,213),'react':(81,145),'vue':(112,234)}[fw]
  cases.append(case('C1',[A(path,*bounds)],[A(test,78,164) if fw=='angular' else A(test,59,182) if fw=='react' else A(test,49,122),A(f'packages/{n}/src/__tests__/review-parallel-real-handle.spec.ts',1,len((ROOT/f'packages/{n}/src/__tests__/review-parallel-real-handle.spec.ts').read_text().splitlines()),'owned-new-test-not-yet-run')],['已逐项核对 query/results/state/error/hasMore 及 loadMore/clear/retry 路由；旧套件通过。','Angular 既有 221–255 用真实 core handle 验证两页及末页；React/Vue 既有主体是 BehaviorSubject 句柄桩，不能算同一真实 core 场景。'],['三端同序列空词→无结果→失败→重试→末页→清空的真实 core handle 新探针已写，主控尚未补跑；因此不把 C1 提前核销。']))
  cases.append(case('C2',[A(path,91,183) if fw=='angular' else A(path,54,124) if fw=='react' else A(path,53,61),A(path,156,204) if fw=='vue' else A(path,*bounds)],[A(test,306,456) if fw=='angular' else A(test,191,368) if fw=='react' else A(test,270,407)],['source/options identity 的重建与当前 query 保留已有断言；initialQuery 只播种、不当作受控输入；语义等价对象不重建。','Vue 已实际读取并核对 options 深修改回归（pageSize/collections）；React snapshot 复制 collections；Angular 接受 Signal。'],['缺 A→B 真正异步查询代次与 branch 变化并发翻页的三端同 fixture；既有桩 emission 隔离不等价于完整搜索后端时序。']))
  cases.append(case('C3',[A(f'packages/{n}/src/index.ts',13 if fw!='react' else 14,17 if fw=='react' else 16),A(path,*bounds)],[A(f'packages/{n}/src/__tests__/readme-consumer.spec.tsx',6,42)] if fw=='react' else [A(test,210,219)] if fw=='angular' else [],['三端根入口同样透传 SearchExecutionError（运行时）、SearchHandle/SearchOptions/SearchResult/SearchState（类型）和 SearchSourceLike/UseSearchReturn。','已读取真实 pack 的发布根/入口清单及独立 root ESM resolve；没有拿 Angular 源 manifest 缺 exports 误报。','React README consumer 只定义函数、由本轮 workspace typecheck 编译；它没有启动数据库或挂载页面。'],['pack 证据未执行声明编译/runtime import；缺插件、backend 不支持、typed root consumer 及同 fixtures parity 的完整消费链路未全部覆盖。']))
  life={'angular':['EnvironmentInjector destroy 确实切断订阅、晚到桩结果不回写；Signal source/options 重建及最新 handle 销毁已有断言。','缺真实组件 input/子 provider 覆盖、组件多实例与 route 反复挂卸。'],'react':['旧 cleanup 先 unsubscribe/destroy，新 layout effect 建 handle；已有真实 StrictMode 两 handle 与 captured callback 指向新 handle 的断言。','缺多个独立 root、真实异步查询快速 props 与卸载后的 core 结果组合。'],'vue':['真实 effectScope 停止后释放 latest handle，SSR 不激活 handle，getter/ref 及深 options 更改已验证局部。','缺真实 SFC 多实例挂卸与旧 core 查询晚到的完整组合；scope 测试不冒充完整 UI。']}[fw]
  cases.append(case('C4',[A(path,*bounds)],[A(test,166,207) if fw=='angular' else A(test,120,146) if fw=='react' else A(test,124,202),A(test,438,455) if fw=='angular' else A(test,371,399) if fw=='react' else A(test,345,405)],[life[0]],[life[1]]))
  cases.append(case('C5',[A(path,48,65) if fw=='angular' else A(path,31,65) if fw=='react' else A(path,69,93),A(f'packages/{n}/src/index.ts',1,17 if fw=='react' else 16)],[],['公开返回字段的 framework idiom 已核对，基线 lint/typecheck 通过；source 与方法执行不在 React render 中发 IO。' if fw=='react' else '公开返回字段与基线 lint/typecheck 已核对。'],['Angular 模板输入/事件错误与真实 route 尚缺。' if fw=='angular' else '错误 props 的独立 strict consumer 与 render/异常边界未完整取证；新 spec 类型门禁需补跑。' if fw=='react' else 'vue-tsc SFC consumer、模板错误、readonly/computed 来源和独立 pack 声明消费尚缺。']))
 elif n.startswith('rxdb-plugin-tree-'):
  path=f'packages/{n}/src/use-tree.ts'; test=f'packages/{n}/src/__tests__/use-tree.spec.ts'; gen=f'packages/{n}/src/__tests__/tri-framework-generics.spec.ts'
  cases.append(case('C1',[A(path,23,81)],[A(test,53,110) if fw=='angular' else A(test,81,128) if fw=='react' else A(test,96,129),A(gen,21,77)],['四个入口逐个对齐方法名/defaultValue（数组 []、计数 0）与 EntityStaticType 参数；只委托本框架 useRepositoryQuery，不存在扁平查询 fallback。','泛型 fixture 有 PlainEntity 编译期拒绝及树实体接受，但 id 实际都是 string，不能拿它证明 numeric id。'],['缺 numeric id 实际查询、无 Tree 插件、QueryCache 禁止组合及深树真实仓储链路；四个同名 mock method 不能替代这些原场景。']))
  base={'angular':('packages/rxdb-angular/src/hooks.ts',45,124),'react':('packages/rxdb-react/src/hooks.ts',71,159),'vue':('packages/rxdb-vue/src/hooks.ts',124,257)}[fw]
  cases.append(case('C2',[A(path,23,81),A(*base)],[A(test,53,110) if fw=='angular' else A(test,99,127) if fw=='react' else A(test,96,128)],['wrapper 没有自己的 query state/订阅；订阅切换和错误全部由已读 useRepositoryQuery 承担，React/Vue 有代次屏障，Angular effect cleanup 释放旧订阅。'],['没有在树 wrapper 上运行跨父移动、父删除、快速改 query、空树与销毁同 fixture；状态模型源码相同不等于真实树增量结果已复验。']))
  cases.append(case('C3',[A(path,23,81),A(f'packages/{n}/src/index.ts',13 if fw=='vue' else 14 if fw=='angular' else 15)],[A(gen,21,77)],['三端四个运行时根导出、输入泛型/资源返回结构一致，类型参数均收紧为 TreeEntityType；计数默认值已动态断言。','已实际读取三端 README 的调用形式、原生成/控制来源是 scope 中的手写 class fixture，不是后台生成的 consumer。'],['缺同一真实 tree fixture 的三端状态/多实例泄漏对照及独立 typed consumer；pack root resolve 不证明声明可消费。']))
  cases.append(case('C4',[A(path,23,81),A(*base)],[],['已追溯到框架核心的 cleanup/代次实现，不在 thin wrapper 另建订阅。'],['Angular 缺真实组件 input/provider override/route；React wrapper 套件没有 StrictMode 与多 root；Vue 套件仅 effectScope，没有真实 SFC props 深改/挂卸/晚到组合。']))
  cases.append(case('C5',[A(path,23,81),A(gen,21,77,'read-test-definition')],[],['现有 workspace typecheck 编译正反泛型 fixture，基线 lint 无警告；没有因为 inject/use 命名差异误报。'],['现有 fixture 不是独立声明 consumer；Angular 模板错误/route、React 同值新引用和错误 props 渲染、Vue vue-tsc/readonly/SFC pack 消费不能由 root resolve 和类型 fixture 自动补齐。']))
 elif n.startswith('rxdb-plugin-replay-'):
  file={'angular':'replayer.component.ts','react':'replayer.tsx','vue':'replayer.ts'}[fw];path=f'packages/{n}/src/{file}';test=f'packages/{n}/src/__tests__/'+{'angular':'replayer.component.spec.ts','react':'replayer.spec.tsx','vue':'replayer.spec.ts'}[fw]; rng={'angular':(50,117),'react':(50,102),'vue':(36,95)}[fw]
  cases.append(case('C1',[A(path,*rng)],[A(test,18,60) if fw=='angular' else A(test,19,58) if fw=='react' else A(test,21,60)],['真实框架组件运行 shared parity：输入原样送 mountReplayer，输入变化仅 update，commands 委托，销毁调用 destroy；React 另有 StrictMode 活视图数守恒。','shared MountReplayerSpy 只观察核心边界，没有加载 rrweb 或真实 recording。'],['空 recording、加载失败、切 recording、双播放器和无后台录制的实际核心/浏览器链路尚缺；React early-seek 候选待主控复验。' if fw=='react' else '空 recording、加载失败、切 recording、双播放器和无后台录制的实际核心/浏览器链路尚缺。']))
  cases.append(case('C2',[A(path,64,76) if fw=='angular' else A(path,58,70) if fw=='react' else A(path,65,69),A('packages/rxdb-plugin-replay/src/testing/replayer-parity.ts',174,184,'read-dependency-test-definition')],[A(test,54,59) if fw=='angular' else A(test,52,57) if fw=='react' else A(test,55,60)],['同一个 dirty_working_tree restore event 在 parity 中保持对象身份；组件仅转发核心事件，不直接更新 HEAD。'],['parity 只有手动触发 restore callback；缺实际 marker 点击、不可达/dirty/并发 restore 与恢复中卸载的加载/拒绝序列。']))
  cases.append(case('C3',[A(f'packages/{n}/src/index.ts',10,12),A(path,*rng)],[A(test,54,59) if fw=='angular' else A(test,52,57) if fw=='react' else A(test,55,60),A('packages/rxdb-plugin-replay/src/testing/replayer-parity.ts',129,213,'read-dependency-test-definition')],['公开 replay/sessionId/initialTime、两个输出和 play/pause/seek 已按框架 idiom 对齐；core 的事件类型及 replayRestoreHint 三端同样透传。','共用七条 parity 不是三份 demo 截图；Vue toRaw 额外保护门面原始对象。'],['缺同 recording/marker 序列的真实 UI、尺寸变化、键盘与错误提示；七条边界桩 parity 不覆盖控件可访问性。']))
  cases.append(case('C4',[A(path,*rng)],[A(test,61,87)] if fw=='react' else [A(test,63,77)] if fw=='angular' else [A(test,64,87)],['Angular 是 OnPush、afterNextRender 安装 + DestroyRef cleanup；React effect cleanup 对应 mount，useEffectEvent 更新回调；Vue onMounted/onBeforeUnmount 与 watch 按输入引用 delta update。','React StrictMode 已实际测试，不列为完全未测；但测试仅证明 mount/destroy 计数。'],['缺销毁中真实 async 完成、同组件多实例/多个 root；Angular 缺 provider/route；Vue 缺 ref/computed/getter 真实父子链路。React first layout seek 另有未跑回归。']))
  cases.append(case('C5',[A(path,*rng),A(f'packages/{n}/src/index.ts',10,12)],[A(test,1,16)],['基线 typed source 与 lint/typecheck 通过，pack 发布入口/目标文件已在真正 tarball 核对；组件的 imperative/output 容器差异是框架表达。'],['独立 typed consumer 未执行；Angular 模板负例/真实 route，React 首次 layout 命令及错误 props，Vue SFC emits/readonly/模板消费仍未完整验证。']))
 elif n.startswith('rxdb-plugin-working-tree-'):
  path=f'packages/{n}/src/use-working-tree.ts'; test=f'packages/{n}/src/__tests__/use-working-tree.'+('spec.tsx' if fw=='react' else 'spec.ts');rng={'angular':(166,190),'react':(81,96),'vue':(150,174)}[fw]
  cases.append(case('C1',[A(path,*rng)],[A(test,69,145) if fw=='angular' else A(test,77,165) if fw=='react' else A(test,94,171)],['初始十二格 idle、创建入口不发 IO；读取 provider 后只创建共享 core commands。','status/diff 是显式方法状态，不是自动订阅；三端 README 明确 entity.save/其他标签页不会自动更新，不把这个已声明行为当 bug。'],['未 enable、缺插件、真实 branch/数据库切换和多实例状态 ownership 未全证；React provider 切 A→B 候选的两条新回归等待主控，不提前算红/绿。']))
  cases.append(case('C2',[A(path,*rng),A('packages/rxdb-plugin-working-tree/src/working-tree/working-tree-commands.ts',125,137,'read-dependency-implementation'),A('packages/rxdb-plugin-working-tree/src/working-tree/working-tree-commands.ts',231,299,'read-dependency-implementation')],[A(test,205,305) if fw=='angular' else A(test,229,332) if fw=='react' else A(test,234,328)],['共享 REJECTED_RESTORES 的四种拒绝与 CAS conflict 原样作为 success/value，switchBranch dirty 拒绝是 error + 原样抛出；状态刷新失败不改变已完成 commit 返回值。','credentials/options 只由共享 commands 透传；wrapper 不自行提交/改 HEAD。'],['缺真实数据层并发点击/CAS 落败不损坏数据以及动作中换 scope；现有 IO fixture 不拥有真正数据库。React 旧 commands 回写新 scope 候选待补跑。']))
  cases.append(case('C3',[A(path,*rng),A(f'packages/{n}/src/index.ts',16 if fw!='react' else 18,17 if fw!='react' else 19)],[A(test,424,497) if fw=='angular' else A(test,458,556) if fw=='react' else A(test,447,520)],['十二个方法与十二格状态实际对齐；类型不重定义/不再导出 core 错误类，这是三端一致的既定 contract，不误报缺失透传。','三端用同官方测试 fixture，但 enableIfEmpty/commitChanges 的 presence guard 不等于执行了这些命令。'],['缺真实应用拒绝序列、关闭期间晚到状态、多实例敏感 diff 摘要/清理以及独立 typed 消费；不能用 100% wrapper coverage 证明 core 历史数据安全。']))
  cases.append(case('C4',[A(path,*rng)],[A(test,53,64) if fw=='angular' else A(test,53,72) if fw=='react' else A('packages/rxdb-plugin-working-tree-vue/src/__tests__/rxdb-provider-harness.ts',1,11),A('packages/rxdb-plugin-working-tree-vue/src/__tests__/setup-harness.ts',1,9)] if fw=='vue' else [A(test,53,72)],['Angular TestBed 注入、React 真 renderHook/provider、Vue 真 mount/provider harness 已辨别；核心 IO 仍是测试桩。','resource 没有独立 Observable 订阅；不能虚构 unsub 测试代替实际 pending command 生命周期。'],['Angular 实际组件销毁/子 provider、多实例；React StrictMode/多 root/旧库 pending（新 probe 未跑）；Vue provider ref 替换与 SFC scope/晚到命令，均未完整证明。']))
  cases.append(case('C5',[A(path,58,111) if fw=='angular' else A(path,42,95) if fw=='react' else A(path,52,105)],[],['Signal / render snapshot / ComputedRef 只改变状态容器；commands 返回 Promise 与 core 结果保持同结构；基线类型和 lint 已过。'],['Angular 模板/route、React 独立 typed consumer + StrictMode 错误 props、Vue vue-tsc/SFC readonly/emits pack consumer 未完整验证；root resolve 是路径证据而非声明/运行证明。']))
 elif n in ['rxdb-angular','rxdb-react','rxdb-vue']:
  base={'angular':('packages/rxdb-angular/src/hooks.ts',45,124),'react':('packages/rxdb-react/src/hooks.ts',71,159),'vue':('packages/rxdb-vue/src/hooks.ts',124,257)}[fw]
  provider={'angular':('packages/rxdb-angular/src/rxdb.provider.ts',56,145),'react':('packages/rxdb-react/src/rxdb-react.tsx',129,248),'vue':('packages/rxdb-vue/src/rxdb-vue.ts',114,236)}[fw]
  cases.append(case('C1',[A(*base)],[],['五项资源状态、空值判断和 errors 转 Error 已读；Angular lazy signal、React layout 代次 + passive 订阅、Vue options key watch + scope invalidation 已逐段追溯。'],['尚未人工逐个公开查询入口与所有原场景映射；快速参数变化/失败重试/晚到真实仓储还缺完整三端共同 fixture。React browser target 不在普通基线 test 中执行。']))
  cases.append(case('C2',[A(f'packages/{n}/src/use-action.ts',23 if fw=='angular' else 56 if fw=='react' else 54,65 if fw=='angular' else 78 if fw=='react' else 71),A(f'packages/{n}/src/use-sync-state.ts',69 if fw=='angular' else 49 if fw=='react' else 63,80 if fw=='angular' else 62 if fw=='react' else 79),A(f'packages/{n}/src/use-persisted-state.ts',69 if fw=='angular' else 90 if fw=='react' else 54,77 if fw=='angular' else 98 if fw=='react' else 117)],[],['三端 action 计数追踪所有并发 promise、finally 归还计数，错误原样 reject，不把 isPending 当实际防重入锁。','syncState 归属 core；persistError 有公开状态，registry 所有权不同（Angular root DI，React/Vue module registry）。'],['连续点击/写入拒绝/换库/离线重连/销毁的完整链路未逐项映射；Angular directive 当前 16 个 fixture/mock 边界失败，不归因生产实现。']))
  nav={'angular':('packages/rxdb-angular/src/InfiniteScrollingList.ts',90),'react':('packages/rxdb-react/src/useInfiniteScroll.ts',83),'vue':('packages/rxdb-vue/src/useInfiniteScroll.ts',129)}[fw]
  cases.append(case('C3',[A(*nav,role='navigation-only-not-deep-read')]+([A('packages/rxdb-angular/src/use-infinite-scroll.ts',50,55)] if fw=='angular' else []),[],[],['分页实现和其大量测试未深读；末页、同值排序、NULL、跨页删除/更新与多列表的原场景全部不能因 unit/coverage 绿自动核销。']))
  cases.append(case('C4',[A(*provider),A(*base)],[],['provider owned/source 生命周期已追踪：直接实例借用，promise/factory 按 scope 销毁；React lease 的 microtask 避开 StrictMode 探测性 cleanup；Vue disposed 后晚到 owned instance 销毁。'],['真实多个 root/provider override/route/输入快速切换未逐项映射；React browser 现有 target 尚待主控；Angular 基线失败需先查 mock/Analog 编译后的 import 边界。']))
  cases.append(case('C5',[A(*base),A(*provider)],[],['本轮 workspace 类型/零警告门禁及真正 tarball root resolve 已实读，不引用旧日期全仓日志。'],['本对象所有受控源码/测试未读完；独立 typed consumer/runtime import/模板/SFC 的真实消费链路不在 pack 证据范围。']))
 elif n=='rxdb-model':
  cases.append(case('C1',[A('packages/rxdb-model/src/entity-form/form-fields.ts',17,47),A('packages/rxdb-model/src/entity-capabilities.ts',33,37),A('packages/rxdb-model/src/entity-form/interfaces.ts',16,55)],[],['create 排除 computed、view 标 readonly、visibility 单独过滤；能力派生依 getEntityPermission 的 both；nullable/enum/relation 等字段属性在共享接口可见。'],['extractEntityFields 的完整 metadata/未注册关系规则及每项对应 UI 验证未读完，不能承诺全部写入能力已正确显示。']))
  cases.append(case('C2',[A('packages/rxdb-model/src/entity-form/form-data.ts',17,83),A('packages/rxdb-model/src/entity-form/form-validation.ts',15,34)],[],['提交差异跳过 readonly，解析字段值后 structuralEqual 比较；validateForm 跳过 hidden/readonly；默认 data 按字段 type 创建。'],['parse/format 严格边界、BigInt/binary/date/非法 JSON/关系改变/保存失败的全部测试体与三端 UI 未读完；原输入恢复缺完整证据。']))
  cases.append(case('C3',[A('packages/rxdb-model/src/entity-table/columns/build-editable-columns.ts',27,role='navigation-only-not-deep-read'),A('packages/rxdb-model/src/entity-table/vtable/table-clipboard.ts',181,role='navigation-only-not-deep-read')],[],[],['表格 columns/query/cursor/保存中 refresh/跨页选择未深审；测试 993 passed 与 coverage 不能替代此 C 的真实 repository 场景映射。']))
  cases.append(case('C4',[A('packages/rxdb-model/src/entity-table/editors/global-overlay-editor.ts',25,47,'navigation-only-not-deep-read'),A('packages/rxdb-model/src/entity-table/vtable/table-clipboard.ts',119,133,'navigation-only-not-deep-read')],[],[],['overlay/图标/SVG/剪贴板相关实现与恶意 HTML/SVG、公式/大数据粘贴、portal 卸载、焦点恢复场景未读完/未动态复验。']))
  cases.append(case('C5',[A('packages/rxdb-model/src/index.ts',6,57),A('packages/rxdb-model/src/entity-form/interfaces.ts',16,116),A('packages/rxdb-model/src/entity-form/form-data.ts',17,83)],[],['已读取的共享 form helpers 没有具体框架 import；三端根入口皆依赖共享 model，form data 与事件结构可追溯。'],['全部共享内核（117 文件）、theme/singleton、同 metadata 三端 fixture、独立 typed/runtime pack 导入与同编辑器多实例未完整证明。']))
  cases.append(case('C6',[A('packages/rxdb-model/src/entity-table/editors/global-overlay-editor.ts',34,47,'navigation-only-not-deep-read')],[],[],['没有当前 1000+ 行耗时/内存测量和真实键盘/aria/弹层焦点证据；不以单元覆盖率或“可进一步审查”替代性能结论。']))
 else:
  forms={'angular':('packages/rxdb-model-angular/src/entity-form/rxdb-entity-form-angular.ts',251,337,'navigation-only-body-not-fully-read'),'react':('packages/rxdb-model-react/src/entity-form/entity-form.tsx',157,245,'read-implementation'),'vue':('packages/rxdb-model-vue/src/entity-form/EntityForm.vue',23,145,'read-implementation')}[fw]
  detail={'angular':('packages/rxdb-model-angular/src/entity-detail/entity-detail.ts',74),'react':('packages/rxdb-model-react/src/entity-detail/entity-detail.tsx',81),'vue':('packages/rxdb-model-vue/src/entity-detail/EntityDetail.vue',42)}[fw]
  listp={'angular':('packages/rxdb-model-angular/src/entity-list/entity-list.component.ts',189),'react':('packages/rxdb-model-react/src/entity-list/entity-list.tsx',197),'vue':('packages/rxdb-model-vue/src/entity-list/EntityList.vue',154)}[fw]
  dialog={'angular':('packages/rxdb-model-angular/src/entity-dialog/entity-dialog.component.ts',26),'react':('packages/rxdb-model-react/src/entity-dialog/entity-dialog.tsx',40),'vue':('packages/rxdb-model-vue/src/entity-dialog/EntityDialog.vue',14)}[fw]
  query={'angular':('packages/rxdb-model-angular/src/query-builder/query-builder/query-builder.component.ts',130),'react':('packages/rxdb-model-react/src/query-builder/query-builder/query-builder.tsx',56),'vue':('packages/rxdb-model-vue/src/query-builder/query-builder/QueryBuilder.vue',25)}[fw]
  cases.append(case('C1',[A(*forms),A(*detail,role='navigation-only-not-deep-read')],[],['React/Vue Form 由输入 data 初始化局部 draft；字段严格解析失败只发 validationErrors、不发 fieldChanged；提交验证后只发 formSubmitted，核心保存归属父详情/consumer。' if fw!='angular' else 'Angular Form 的输入/output/linkedSignal 位置已定位，但主要函数体、父详情保存链路未全部读取。'],['完整字段/关系/readonly/format/NEW-UPDATE 与父组件保存失败/输入恢复未逐项完成；不能把 form 本地事件等价成持久化成功。']))
  cases.append(case('C2',[A(*listp,role='navigation-only-not-deep-read')],[],[],['实例 remove / mutations 两类真实写入口、权限拒绝/并发保存/跨页选择/NULL 同值排序/删除失败未深读。已有 *.real.spec 命名不证明真 SQLite/PG：测试 fixture 和 fake VTable 的来源未完成内容审查。']))
  cases.append(case('C3',[A(*dialog,role='navigation-only-not-deep-read'),A(*query,role='navigation-only-not-deep-read')],[],[],['Dialog/QueryBuilder/portal 的焦点/ESC/aria、保存中关闭、恶意文本与卸载未完成内容及真实浏览器复验；不借 300+ passed 抹平未知。']))
  cases.append(case('C4',[A(*forms),A(*query,role='navigation-only-not-deep-read')],[],['只对已读取的 React/Vue Form 回传所有权做了局部对照；data 替换会同步/重置局部 draft，fieldChanged/formSubmitted 分别归属不同动作。' if fw!='angular' else '输入/事件根入口与共享表单契约已定位；此 C 的完整生命周期暂不下通过结论。'],['Angular route/子 provider/销毁中保存，React StrictMode/多 root/async 旧 props，Vue deep props/readonly/computed/真实 SFC scope 均未全证；大量源码和测试尚未深读。']))
  cases.append(case('C5',[A(f'packages/{n}/src/index.ts',7 if fw!='vue' else 9,25 if fw!='vue' else 27),A(*forms)],[],['根导出的表单/详情/列表/表格/QueryBuilder 家族与共享 model 依赖已经定位；真正包内入口及 root ESM resolve 通过。'],['尚缺独立 typed consumer/runtime import、模板或 SFC 负例及完整 UI 链路；TS/Vue 生成声明不由 root resolve 自动证明；本对象非全范围阅读完成。']))
 for entry,row in zip(cases,original[n]):entry.update(row)
 matrix[n]=cases

# 阅读证明只登记本轮真实可见内容；导航扫描和 hash 盘点不冒充全文阅读。
files=[]
for o in scope:
 for path,expected in o['sourceSha256'].items():
  rr=[r for r in reads['reads'] if r['path']==path]; buf=(ROOT/path).read_bytes(); count=len(buf.decode().splitlines()); ranges=[]
  for r in rr:
   if r['mode'] in ('full','implementation'):
    bounds=r.get('range') or [1,count]
    if bounds[0]<=bounds[1]: ranges.append([max(1,bounds[0]),min(count,bounds[1])])
  refs=[(c['C'],a) for c in matrix[o['object']] for a in c['anchors']+c['testAnchors'] if a['path']==path]
  functions=sorted({(ROOT/path).read_text().splitlines()[a['start']-1].strip() for _,a in refs if a['start']<=count and 'navigation' not in a['role'] and 'not-yet-run' not in a['role']})
  status='partial-visible-content' if rr and any(r['mode']!='outline' for r in rr) else 'outline-only' if rr else 'navigation-only' if refs else 'not-manually-inspected'
  files.append({'path':path,'absolutePath':str(ROOT/path),'object':o['object'],'sha256':hashlib.sha256(buf).hexdigest(),'scopeMatches':hashlib.sha256(buf).hexdigest()==expected,'reviewLevel':status,'requestedReadRanges':ranges,'displayCaveat':'存在终端中段截断；requestedReadRanges 不等价于逐行完成。只以 C 明列函数/断言为已证，不给全文件完成标签。','functionsOrStatementsActuallyMapped':functions,'C':sorted({c for c,_ in refs}),'testCoverageOfC':'全 C 未核销。'+('关联测试定义/范围已读；是否覆盖原完整场景逐项见 c-evidence.json。' if '/__tests__/' in path else '不是测试覆盖证明。')})
reads['files']=files; reads['date']='2026-10-05';reads['headAtDelivery']=head; reads['wholeScopeReadComplete']=False;reads['scopeControlledFileCount']=len(files);reads['additionalOwnedSpecs']=json.loads((B/'new-specs.json').read_text());reads['documentationOnlyNow']=True
(B/'file-inspection.json').write_text(json.dumps(reads,ensure_ascii=False,indent=2)+'\n')
(B/'c-evidence.json').write_text(json.dumps({'date':'2026-10-05','baseline':head,'objects':matrix,'completeCCount':0,'partialCCount':sum(map(len,matrix.values())),'completeObjectCandidates':[],'interpretation':'局部场景通过与完整原 C 核销严格区分；新增探针尚未在本轮已有基线日志内。'},ensure_ascii=False,indent=2)+'\n')
(B/'validation-observations.json').write_text(json.dumps({'date':'2026-10-05','head':head,'globalFrameworkCoverage':'22/23 unit suites passed and fresh four metrics; own scope 18/19 passed; Angular 16 failed no fresh summary','log':str(V/'framework-editor-coverage.txt'),'status':str(V/'framework-editor-coverage-status.json'),'gate':str(V/'coverage-gate.json'),'objects':coverage,'lint':{'status':str(V/'all-object-strict-lint-status.json'),'exitCode':validation['strict-lint']['exitCode'],'inputDrift':validation['strict-lint']['changedInputsDuringMeasurement'],'scope':'69 objects, baseline only; late specs require focused rerun'},'typecheck':{'status':str(V/'all-object-typecheck-status.json'),'exitCode':validation['typecheck']['exitCode'],'inputDrift':validation['typecheck']['changedInputsDuringMeasurement'],'scope':'69 objects plus 51 dependency tasks, baseline only'},'pack':{'path':str(V/'packed-consumer-entry-check.json'),'requested':packed['totalRequested'],'entriesPassed':packed['packagedEntryChecksPassed'],'rootResolutionExitCode':packed['resolutionExitCode'],'declarationCompilationExecuted':packed['declarationCompilationExecuted'],'runtimeImportExecuted':packed['runtimeImportExecuted'],'source':'real pnpm tarballs from resolved publishedPackageRoot, independent extracted consumer without workspace paths/symlinks'},'logSections':sections,'lateProbeExecution':'pending main control; not counted in baseline test/coverage/lint/typecheck'},ensure_ascii=False,indent=2)+'\n')

family_notes={
 'search':'输入 query 是 consumer 所有；结果/state/error/hasMore 归属 core handle。重建先 unsubscribe/destroy 旧 handle；命令通过 active/ref 路由最新 handle。initialQuery 仅初次种子，不能当作 v-model/受控 query。Angular 清空 last 防二次 setQuery，Vue suppressedQuery 同样防 clear 回声；React clear 更新 queryRef。',
 'tree':'四个函数只挑静态仓储方法名与默认值，没有第二套 query 状态机。生命周期和错误归属对应 rxdb framework useRepositoryQuery；Tree 插件拥有层级/QueryCache/移动语义。当前 fixture 是手写 TreeEntity/static method mock，不是深树 SQL 或 numeric-id consumer。',
 'replay':'component props/signals 是输入，core mountReplayer 拥有真实播放器/restore/rrweb 生命周期；framework output 只是转发，不更新 HEAD。shared parity 通过手动触发 callback 验证事件对象身份，不能代替真实 marker 点击与恢复。React useEffectEvent 绑定最新 callback，Vue toRaw 保留 ReplayManager 私有字段的原对象身份。',
 'working-tree':'十二格状态 + 十二个 core commands；没有 Observable 自动变更流，只有本入口执行动作才 patch。查询 empty 与命令 success/reject 的区别保留 core contract，CAS/restore 返回值不是 throw。React state/patch 稳定闭包跨库 ownership 有待复验；另外两端不未经复验归为同一根因。',
 'model':'共享内核与 Form 局部 draft/fieldChanged/formSubmitted 已分层，事件通知不是数据库保存成功。大批 table/list/query-builder/overlay/真实 UI 测试内容未读完，*.real.spec 名称不自动升级为真正 repository/browser 证据。',
 'core':'查询五状态、provider 借用/owned lease、sync/persist/action 的局部实现已读；分页和大量测试未完整阅读，不能以全包 coverage 承诺游标/真实 route/StrictMode 全场景。'
}
changed=[]
for o in scope:
 n=o['object']; cs=matrix[n]; cov=coverage[n]; pak=packs[n]; fs=[f for f in files if f['object']==n]; content=sum(f['reviewLevel']=='partial-visible-content' for f in fs); outline=sum(f['reviewLevel']=='outline-only' for f in fs); nav=sum(f['reviewLevel']=='navigation-only' for f in fs); unseen=sum(f['reviewLevel']=='not-manually-inspected' for f in fs)
 family='search' if 'plugin-search' in n else 'tree' if 'plugin-tree' in n else 'replay' if 'plugin-replay' in n else 'working-tree' if 'plugin-working-tree' in n else 'model' if 'model' in n else 'core'
 metrics=cov['coverage']; metricstr=' / '.join(f"{metrics[k]:g}%" for k in ['statements','branches','functions','lines']) if metrics else '无本轮 fresh coverage-summary（unit 失败）'
 sec=sections.get(n,{}); summaries='；'.join(t for _,t in sec.get('summary',[])) or '主控基线日志对应项目段；不以 run-many 总 exitCode 判断本包';logrange=sec.get('range',[])
 block=['\n## 2026-10-05 frameworks 并行评审：逐 C 实际交付','',f'基线 `{head}`；唯一范围 `{o["sourceRoot"]}` 的 {o["trackedFileCount"]} 个受控文件，摘要与 scope.json 全部相符。**execution: partial；完整 C 核销 0/{len(cs)}，本对象不是完整完成候选。** 不把已证局部场景当作原完整 C。','',f'阅读登记：{content} 个文件有正文片段、{outline} 个仅测试 outline、{nav} 个仅导航锚点、{unseen} 个未人工检查。正文登记不等价于全文件阅读；截断/函数范围及测试覆盖差别详见 `{B / "file-inspection.json"}`。', '', '### 当前动态证据（限定真实测量面）','', '| 门禁 | 2026-10-05 已读取结果 | 证据 / 边界 |','| --- | --- | --- |',f'| unit | {summaries} | `{V / "framework-editor-coverage.txt"}` 行 {"–".join(map(str,logrange)) if logrange else "见项目段"}；新增 review-parallel 不在此基线 |',f'| 四项覆盖率 | statements / branches / functions / lines = {metricstr}；要求各项 ≥ {cov["policyFloor"]}% | `{V / "coverage-gate.json"}`；原 include/exclude、禁缓存、maxWorkers=1；{"达标但不代替 C 语义" if metrics else "失败，无覆盖率通过结论"} |',f'| lint / typecheck | 全 69 对象分别 exitCode=0；typecheck 含 51 依赖任务，输入无漂移 | `{V / "all-object-strict-lint-status.json"}`、`{V / "all-object-typecheck-status.json"}`；新 spec 仍待 focused rerun |',f'| 实际 pack / root resolve | {pak["packedFileCount"]} 个包内文件，declared entries 缺失 0；root 解析通过 | `{V / "packed-consumer-entry-check.json"}`；发布根 `{pak["resolvedPublishedPackageRoot"]}`；未执行 typed consumer/runtime import |','','全局框架/editor 队列是 22/23 通过，**本子任务范围为 18/19 通过**；唯 rxdb-angular 的 16 个 directive fixture/mock 边界失败。这里不借另外 4 个 editor 包的数据补足自身对象。','','### 功能族、订阅生命周期与双向事件所有权','',family_notes[family],'','### 逐 C 结论（原场景没有缩小）','']
 for c in cs:
  block += [f'#### {c["C"]} {c["title"]} — partial','',f'原动作：{c["action"]}',f'原最低场景：{c["originalScenario"]}','', '**已证结论**：' + ('；'.join(c['established']) if c['established'] else '未形成通过结论；只登记当前入口，不声称实现或测试已完整评审。'),'','**源码 / 类型锚点**：']
  for a in c['anchors']:block.append(f'- `{a["absolutePath"]}:{a["start"]}–{a["end"]}`（{a["role"]}）')
  if c['testAnchors']:
   block.append('**实际读取的测试定义/新增探针**：')
   for a in c['testAnchors']:block.append(f'- `{a["absolutePath"]}:{a["start"]}–{a["end"]}`（{a["role"]}）')
  block += ['','**必要缺口 / 不能核销原因**：'+'；'.join(c['gaps']),'']
 block += ['### 全对象完成条件逐条判定','',f'1. **全部受控文件清点：通过；全部内容阅读：partial。** {len(fs)} 个全范围文件已登记，{unseen} 个仍未人工检查；不从 scope 默默删配置、fixture、README、资源。','2. **逐 C 明确结论与原场景登记：通过；原完整 C 核销：未完成。** 每条保留原动作/场景和局部证据，缺必要验证不是完成。','3. **源码不变量 / 动态主张分离：通过（已登记范围）。** read-implementation 与 navigation-only 标注分离；新增探针不引用预期红当实际失败。','4. **当轮门禁、缓存、skip、四指标：基线已登记。** 当前报告原测量面不变；晚加 spec 没有被老 baseline 自动覆盖。'+(' Angular 当前 unit 红且没有 fresh summary，整体包/coverage 均不通过。' if n=='rxdb-angular' else ''),'5. **上游 / 三端 / 消费链路：partial。** 已作公开根入口、类型/容器、delegation/所有权局部对照；pack 不等于独立 typed/runtime consumer，完整 UI 链路见各 C 缺口。','6. **问题去重 / 正式结论：partial。** 仅 React working-tree/provider 和 replay/early-seek 两个候选在 findings.pending.md 待主控复验/去重编号；不生成 RV，不扩新问题。','7. **全对象评级与完成：不核销。** 没有把“后续可审”“测试很多”“100% thin wrapper coverage”当作完成；评审完成不要求零缺陷，但仍要求原场景/全范围有证据。','','### 交付附件','',f'- `{B / "c-evidence.json"}`：原场景、结论、源码/测试角色、具体缺口。',f'- `{B / "file-inspection.json"}`：完整受控 inventory、真实正文/outline/导航的区别与摘要。',f'- `{B / "validation-observations.json"}`：已读取的主控测量与 pack 消费来源。',f'- `{B / "findings.pending.md"}`：只保留两个候选及 Angular 门禁边界。',f'- `{B / "validation-requests.json"}`：已请求的 late spec focused 验证；本交付不等待更大队列。','']
 rp=ROOT/o['record'];text=rp.read_text(); marker='\n## 2026-10-05 frameworks 并行评审：逐 C 实际交付';text=text.split(marker)[0];rp.write_text((text.rstrip()+'\n'+'\n'.join(block)).rstrip()+'\n');changed.append(str(rp))
 pp=ROOT/o['plan'];ptext=pp.read_text(); ptext=re.sub(r'^(\| C\d+\s*\|.*?\|)[^|]*\|\s*$',lambda m:m[1]+' partial |',ptext,flags=re.M);pmarker='\n## 2026-10-05 frameworks 本轮完成条件与实际核查';ptext=ptext.split(pmarker)[0]
 pblock=[pmarker,'',f'本轮 `main/worktree@{head}`，日期 2026-10-05。不是新泛计划，而是对原 C 的实际结论：**0/{len(cs)} 个完整 C、execution 保持 in-progress；结果记录保持 partial；本对象不是全对象完成候选。**','',f'全部 {o["trackedFileCount"]} 个受控文件的范围/摘要已核对，正文片段 {content}、outline {outline}、仅导航 {nav}、未人工检查 {unseen}；不能将 scope 盘点称为全读。','', '| 原 C | 本轮结论 | 原场景中仍缺的必要证据 |','| --- | --- | --- |']
 for c in cs:pblock.append(f'| {c["C"]} {c["title"]} | partial；{"局部通过" if c["established"] else "未验证"} | {"；".join(c["gaps"]).replace("|","/")} |')
 pblock += ['', '本轮完成条件：','', '- [x] 全受控 inventory / 摘要核对，未排除配置/资源/fixture。','- [ ] 全部受控内容阅读及全部原 C 场景核销（缺口见表，保持 partial）。','- [x] 每 C 已有明确的已证/未证结论及角色明确的源码、测试锚点。','- [x] 当前 baseline 的 unit / 四指标 / 零警告 lint / typecheck / 真 pack 来源已读取登记。','- [ ] 晚加探针补跑、独立 typed/runtime consumer、真实完整 UI/生命周期等必要缺口全部关闭。','- [ ] 全对象证据完成与最终评级（不要求零缺陷，但不能缺验证）；尚未完成。','',f'本对象四指标（statements/branches/functions/lines）：**{metricstr}**；阈值各项 ≥ {cov["policyFloor"]}%。其余18包的绿不能抹掉 rxdb-angular 的16个失败；新探针不继承基线通过。',f'发布 pack 根是 `{pak["resolvedPublishedPackageRoot"]}`，实际 tarball 目标文件存在、独立根 ESM 解析通过；**不包含 typed consumer 编译/runtime import**。Angular 不能按源 manifest 缺 exports 报错。','',f'逐 C 原场景、函数/测试证据与完成条件详见 `{rp}`；机器证据 `{B / "c-evidence.json"}` / `{B / "file-inspection.json"}`。','']
 pp.write_text((ptext.rstrip()+'\n'+'\n'.join(pblock)).rstrip()+'\n');changed.append(str(pp))

# 保存仍需补跑请求；已完成 baseline 请求保留到 archived 文件，不催主控重复整轮任务。
req=json.loads((B/'validation-requests.json').read_text());(B/'validation-requests.baseline.json').write_text(json.dumps(req,ensure_ascii=False,indent=2)+'\n');pending=[]
for r in req:
 if r['target']=='test-browser' or 'src/__tests__/review-parallel-' in r['reason'] or '基线验证之后新增 review-parallel' in r['reason']:
  if r not in pending:pending.append(r)
(B/'validation-requests.json').write_text(json.dumps(pending,ensure_ascii=False,indent=2)+'\n')
changed += [str(p) for p in B.iterdir() if p.is_file() and p.name!='scope.json']
changed += [str(ROOT/x['path']) for x in json.loads((B/'new-specs.json').read_text())]
changed=sorted(set(changed));summary={'date':'2026-10-05','scopeObjects':len(scope),'controlledFiles':len(files),'completeC':0,'partialC':sum(map(len,matrix.values())),'completeObjectCandidates':[],'execution':'partial','unitBaselinePassedInScope':18,'unitBaselineFailedInScope':['rxdb-angular'],'coveragePassedInScope':18,'packRootResolutionPassedInScope':19,'baselineLintAndTypecheckPassedInScope':19,'newOwnedSpecs':5,'pendingValidationRequests':len(pending),'findingCandidates':['FW-WORKING-TREE-PROVIDER','FW-REPLAYER-EARLY-SEEK'],'noProductionChange':True,'noNestedAgent':True,'noHeavyTaskExecutedBySubtask':True,'noGitMutation':True,'changedPaths':changed}
(B/'delivery-summary.json').write_text(json.dumps(summary,ensure_ascii=False,indent=2)+'\n');changed.append(str(B/'delivery-summary.json'));(B/'changed-files.json').write_text(json.dumps(sorted(set(changed+[str(B/'changed-files.json')])),ensure_ascii=False,indent=2)+'\n')
print(json.dumps({k:v for k,v in summary.items() if k!='changedPaths'},ensure_ascii=False,indent=2));print('changed paths',len(json.loads((B/'changed-files.json').read_text())))
