export const STORAGE_TESTID = {
  PAGE: 'storage-page',
  UPLOAD_BTN: 'storage-upload-btn',
  UPLOAD_FOLDER_BTN: 'storage-upload-folder-btn',
  FILE_INPUT: 'storage-file-input',
  FOLDER_INPUT: 'storage-folder-input',
  FILE_LIST: 'storage-file-list',
  FILE_ROW: 'storage-file-row',
  FILE_NAME: 'storage-file-name',
  FILE_SIZE: 'storage-file-size',
  FILE_TYPE: 'storage-file-type',
  FILE_PATH: 'storage-file-path',
  FILE_VERSION: 'storage-file-version',
  NEW_FOLDER_BTN: 'storage-new-folder-btn',
  NEW_FOLDER_DIALOG: 'storage-new-folder-dialog',
  NEW_FOLDER_INPUT: 'storage-new-folder-input',
  NEW_FOLDER_CONFIRM: 'storage-new-folder-confirm',
  CLEAR_SELECTION_BTN: 'storage-clear-selection-btn',
  BATCH_DOWNLOAD_BTN: 'storage-batch-download-btn',
  BATCH_DELETE_BTN: 'storage-batch-delete-btn',
  PREVIEW_BTN: 'storage-preview-btn',
  DOWNLOAD_BTN: 'storage-download-btn',
  DELETE_BTN: 'storage-delete-btn',
  CLEAR_BTN: 'storage-clear-btn',
  CONFIRM_DIALOG: 'storage-confirm-dialog',
  CONFIRM_YES: 'storage-confirm-yes',
  CONFIRM_NO: 'storage-confirm-no',
  PREVIEW_MODAL: 'storage-preview-modal',
  PREVIEW_CLOSE: 'storage-preview-close',
  CONTEXT_MENU: 'storage-context-menu',
  CONTEXT_VIEW: 'storage-context-view',
  CONTEXT_DOWNLOAD: 'storage-context-download',
  CONTEXT_RENAME: 'storage-context-rename',
  CONTEXT_DELETE: 'storage-context-delete',
  RENAME_DIALOG: 'storage-rename-dialog',
  RENAME_INPUT: 'storage-rename-input',
  RENAME_CONFIRM: 'storage-rename-confirm',
  EMPTY_STATE: 'storage-empty-state',
  ERROR_TOAST: 'storage-error-toast',
  SUCCESS_TOAST: 'storage-success-toast'
} as const;

export const STORAGE_LABELS = {
  PAGE_TITLE: 'Storage',
  UPLOAD: 'Upload File',
  DOWNLOAD: 'Download',
  DELETE: 'Delete',
  CLEAR_ALL: 'Clear All',
  PREVIEW: 'Preview',
  CONFIRM_DELETE: 'Are you sure you want to delete this file?',
  CONFIRM_CLEAR: 'Are you sure you want to clear all files?',
  FILE_TOO_LARGE: 'File is too large to preview',
  FILE_EXISTS: 'File already exists',
  UPLOAD_SUCCESS: 'File uploaded successfully',
  DELETE_SUCCESS: 'File deleted successfully',
  CLEAR_SUCCESS: 'All files cleared',
  NO_FILES: 'No files uploaded yet',
  COL_NAME: 'Name',
  COL_SIZE: 'Size',
  COL_TYPE: 'Type',
  COL_PATH: 'Path',
  COL_VERSION: 'Version',
  COL_CREATED: 'Created',
  COL_UPDATED: 'Updated',
  COL_ACTIONS: 'Actions'
} as const;
