import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  tutorialSidebar: [
    {
      type: 'category',
      label: '开始使用',
      collapsed: true,
      link: {
        type: 'doc',
        id: 'getting-started/README'
      },
      items: ['getting-started/install']
    },
    {
      type: 'category',
      label: '模型定义',
      collapsed: true,
      link: {
        type: 'doc',
        id: 'model-definition/README'
      },
      items: [
        'model-definition/properties',
        'model-definition/relations',
        'model-definition/indexes',
        'model-definition/cascade',
        'model-definition/structure-tree'
      ]
    },
    {
      type: 'category',
      label: '模型查询',
      collapsed: true,
      link: {
        type: 'doc',
        id: 'model-query/README'
      },
      items: [
        {
          type: 'category',
          label: '基础查询',
          items: [
            'model-query/get',
            'model-query/find',
            'model-query/findAll',
            'model-query/findOne',
            'model-query/findOneOrFail',
            'model-query/findByCursor',
            'model-query/count'
          ]
        },
        {
          type: 'category',
          label: '树形结构查询',
          items: [
            'model-query/findDescendants',
            'model-query/findAncestors',
            'model-query/countDescendants',
            'model-query/countAncestors'
          ]
        },
        {
          type: 'category',
          label: '图结构查询',
          items: ['model-query/findNeighbors', 'model-query/countNeighbors', 'model-query/findPaths']
        },
        'model-query/operators',
        'model-query/query-realtime',
        'model-query/exists-operator'
      ]
    },
    {
      type: 'category',
      label: '模型修改',
      collapsed: true,
      link: {
        type: 'doc',
        id: 'model-mutation/README'
      },
      items: ['model-mutation/create', 'model-mutation/update', 'model-mutation/delete', 'model-mutation/transaction']
    },
    {
      type: 'category',
      label: '框架集成',
      collapsed: true,
      link: {
        type: 'doc',
        id: 'frameworks/README'
      },
      items: ['frameworks/react', 'frameworks/vue', 'frameworks/angular']
    },
    {
      type: 'category',
      label: '数据库适配器',
      collapsed: true,
      link: {
        type: 'doc',
        id: 'adapters/README'
      },
      items: ['adapters/sqlite', 'adapters/pglite', 'adapters/supabase']
    },
    {
      type: 'category',
      label: '数据协作',
      collapsed: true,
      link: {
        type: 'doc',
        id: 'collaboration/README'
      },
      items: ['collaboration/branch', 'collaboration/sync', 'collaboration/undo-redo']
    },
    {
      type: 'category',
      label: '插件',
      collapsed: true,
      items: [
        {
          type: 'doc',
          label: '编写插件',
          id: 'plugins/authoring'
        },
        {
          type: 'doc',
          label: 'rxdb-plugin-storage',
          id: 'plugins/rxdb-plugin-storage/README'
        },
        {
          type: 'category',
          label: 'rxdb-plugin-graph',
          collapsed: true,
          link: {
            type: 'doc',
            id: 'plugins/rxdb-plugin-graph/README'
          },
          items: ['plugins/rxdb-plugin-graph/graph-entity']
        },
        {
          type: 'doc',
          label: 'rxdb-plugin-workspace',
          id: 'plugins/rxdb-plugin-workspace/README'
        },
        {
          type: 'doc',
          label: 'rxdb-plugin-search',
          id: 'plugins/rxdb-plugin-search/README'
        }
      ]
    },
    {
      type: 'doc',
      label: '客户端生成',
      id: 'client-generator'
    },
    {
      type: 'category',
      label: '迁移指南',
      collapsed: true,
      link: {
        type: 'doc',
        id: 'migration/README'
      },
      items: [
        'migration/v1',
        'migration/frameworks',
        'migration/adapters',
        'migration/desktop-split',
        'migration/plugins',
        'migration/plugin-scope',
        'migration/schema'
      ]
    },
    {
      type: 'doc',
      label: '版本兼容矩阵',
      id: 'compatibility'
    },
    {
      type: 'doc',
      label: '版本与 API 稳定性策略',
      id: 'versioning'
    },
    {
      type: 'category',
      label: 'API 文档',
      collapsed: true,
      link: {
        type: 'doc',
        id: 'api/README'
      },
      items: [
        {
          type: 'category',
          label: '核心模块',
          items: [
            {
              type: 'autogenerated',
              dirName: 'api/rxdb'
            }
          ]
        },
        {
          type: 'category',
          label: '适配器',
          items: [
            { type: 'autogenerated', dirName: 'api/rxdb-adapter-wa-sqlite' },
            { type: 'autogenerated', dirName: 'api/rxdb-adapter-pglite' },
            { type: 'autogenerated', dirName: 'api/rxdb-adapter-supabase' },
            { type: 'autogenerated', dirName: 'api/rxdb-adapter-sqlite' },
            { type: 'autogenerated', dirName: 'api/rxdb-adapter-sqlite-core' },
            { type: 'autogenerated', dirName: 'api/rxdb-adapter-sqlite-wasm' },
            { type: 'autogenerated', dirName: 'api/rxdb-adapter-sqliteai' },
            { type: 'autogenerated', dirName: 'api/rxdb-adapter-encrypted' }
          ]
        },
        {
          type: 'category',
          label: '框架集成',
          items: [
            { type: 'autogenerated', dirName: 'api/rxdb-angular' },
            { type: 'autogenerated', dirName: 'api/rxdb-react' },
            { type: 'autogenerated', dirName: 'api/rxdb-vue' }
          ]
        },
        {
          type: 'category',
          label: '插件',
          items: [
            { type: 'autogenerated', dirName: 'api/rxdb-plugin-graph' },
            { type: 'autogenerated', dirName: 'api/rxdb-plugin-workspace' },
            { type: 'autogenerated', dirName: 'api/rxdb-plugin-storage' },
            { type: 'autogenerated', dirName: 'api/rxdb-plugin-search' },
            { type: 'autogenerated', dirName: 'api/rxdb-plugin-search-angular' },
            { type: 'autogenerated', dirName: 'api/rxdb-plugin-search-react' },
            { type: 'autogenerated', dirName: 'api/rxdb-plugin-search-vue' }
          ]
        },
        {
          type: 'category',
          label: '代码编辑器',
          items: [
            { type: 'autogenerated', dirName: 'api/code-editor' },
            { type: 'autogenerated', dirName: 'api/code-editor-angular' },
            { type: 'autogenerated', dirName: 'api/code-editor-react' },
            { type: 'autogenerated', dirName: 'api/code-editor-vue' }
          ]
        },
        {
          type: 'category',
          label: '工具与开发者工具',
          items: [
            { type: 'autogenerated', dirName: 'api/utils' },
            { type: 'autogenerated', dirName: 'api/rxdb-client-generator' },
            { type: 'autogenerated', dirName: 'api/rxdb-devtools' }
          ]
        }
      ]
    }
  ]
};

export default sidebars;
